[package]
name = "glide-cli"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
regex = "1.11.1"
tokio = { version = "1.42.0", features = ["full"] }
utils = { git = "https://github.com/ngpal/glide-utils-rs.git"}
